### ISSUE TITLE
ValueError: only support theme icon.

### ISSUE THREAD

**Issue by behind1231** [Xinkai/XwareDesktop#135]
发行版: Arch Linux 
桌面环境: KDE/kde-plasma
应用程序版本: 82957f2593b267a8b312fb4d0bc5189fa68d67f5

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 272, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 90, in __init__
    self.systray = Systray(self)
  File "/opt/xware-desktop/frontend/Widgets/systray.py", line 19, in __init__
    self.setIcon(icon)
  File "/opt/xware-desktop/frontend/Widgets/_KdeSystemTrayIcon.py", line 485, in setIcon
    raise ValueError("only support theme icon.")
ValueError: only support theme icon.
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
应该随 #161 修复了。
