### ISSUE TITLE
No module named _ssl

### ISSUE THREAD

**Issue by badwtg1111** [Xinkai/XwareDesktop#153]
发行版: Ubuntu precise (12.04.5 LTS) 12.04
桌面环境: Unity/ubuntu
应用程序版本: 82957f2593b267a8b312fb4d0bc5189fa68d67f5

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 272, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 71, in __init__
    from models import TaskModel, AdapterManager, ProxyModel
  File "/opt/xware-desktop/frontend/models/__init__.py", line 5, in <module>
    from .ProxyModel import ProxyModel
  File "/opt/xware-desktop/frontend/models/ProxyModel.py", line 13, in <module>
    from libxware.definitions import VipChannelState, LixianChannelState
  File "/opt/xware-desktop/frontend/libxware/__init__.py", line 3, in <module>
    from .adapter import XwareAdapter
  File "/opt/xware-desktop/frontend/libxware/adapter.py", line 17, in <module>
    from .vanilla import TaskClass, XwareClient, Settings
  File "/opt/xware-desktop/frontend/libxware/vanilla.py", line 8, in <module>
    import asyncio, aiohttp
  File "/opt/xware-desktop/frontend/../shared/thirdparty/aiohttp/__init__.py", line 7, in <module>
    from .connector import *
  File "/opt/xware-desktop/frontend/../shared/thirdparty/aiohttp/connector.py", line 9, in <module>
    import ssl
  File "/opt/python/lib/python3.4/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named '_ssl'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
抱歉，本软件对Ubuntu 14.04以前的版本不提供支持。在不支持的平台上出现的问题需要自己解决。
#144 的作者有在Ubuntu12.04上安装成功的经验，你有问题可以问他。
