### ISSUE TITLE
linuxmint17.1 install XwareDesktop failture

### ISSUE THREAD

**Issue by dove924** [Xinkai/XwareDesktop#173]
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 272, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 102, in __init__
    self.mainWin = main.MainWindow(None)
  File "/opt/xware-desktop/frontend/legacy/main.py", line 24, in __init__
    self.connectUI()
  File "/opt/xware-desktop/frontend/legacy/main.py", line 41, in connectUI
    app.systray.toggleMinimized.connect(self.toggleMinimized)
AttributeError: 'Systray' object has no attribute 'toggleMinimized'
```

**Comment by Xinkai** [comment]
你的错误报告不完整。下次把完整的贴上来。

**Comment by dove924** [comment]
Running on the linuxmint17 command line： xware-desktop 
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 20: not well-formed (invalid token)
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 20: invalid attribute 'name'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 20: invalid attribute 'mode'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 20: invalid attribute 'target'
Qt[WARN] default void QSystemTrayIcon::setVisible(bool) in util/qsystemtrayicon.cpp, on line 271
    QSystemTrayIcon::setVisible: No Icon set
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 272, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 102, in __init__
    self.mainWin = main.MainWindow(None)
  File "/opt/xware-desktop/frontend/legacy/main.py", line 24, in __init__
    self.connectUI()
  File "/opt/xware-desktop/frontend/legacy/main.py", line 41, in connectUI
    app.systray.toggleMinimized.connect(self.toggleMinimized)
AttributeError: 'Systray' object has no attribute 'toggleMinimized'
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/util.py", line 252, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.4/multiprocessing/util.py", line 185, in __call__
    res = self._callback(*self._args, **self._kwargs)
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/winxin/.xware-desktop/profile/tmp/xware_frontend.socket'
winxin@winxin ~ $ Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 20: not well-formed (invalid token)
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 20: invalid attribute 'name'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 20: invalid attribute 'mode'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 20: invalid attribute 'target'


Date: Sat, 14 Mar 2015 08:36:20 -0700

**Comment by Xinkai** [comment]
上次我说报告不完整的意思是，你没有提供你的操作系统和XwareDesktop的版本号。
没有这两项东西，我不好判断问题出在哪里

**Comment by dove924** [comment]
Date: Thu, 16 Apr 2015 21:32:33 -0700
