### ISSUE TITLE
Error in Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by Nobler** [Xinkai/XwareDesktop#180]
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 85, in __init__
    from Widgets.systray import Systray
  File "/opt/xware-desktop/frontend/Widgets/__init__.py", line 15, in <module>
    from ._KdeSystemTrayIcon import KdeSystemTrayIcon as CompatSystemTrayIcon
  File "/opt/xware-desktop/frontend/Widgets/_KdeSystemTrayIcon.py", line 12, in <module>
    from Extensions.DBusTypes import DBusTypes
RuntimeError: the sip module implements API v11.0 but the DBusTypes module requires API v11.1

**Comment by Xinkai** [comment]
你可能使用了不同版本的qt，重装本软件试过吗

**Comment by Nobler** [comment]
重装过，也在本机编译过，都不行。

**Comment by Xinkai** [comment]
估计可能用了某个Qt的PPA了。

**Comment by Xinkai** [comment]
可以列一下使用的第三方源吗？大概是冲突了。

**Comment by Xinkai** [comment]
清理长期无进展问题
