### ISSUE TITLE
error

### ISSUE THREAD

**Issue by volcanosc** [Xinkai/XwareDesktop#182]
发行版: Ubuntu 14.04.1 LTS 14.04(Linuxmint 17.1)
桌面环境: 未知/default
应用程序版本: 90b06fd5a92548206834f572e3b2a51662fedf97

failed when start 

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 272, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 90, in __init__
    self.systray = Systray(self)
  File "/opt/xware-desktop/frontend/Widgets/systray.py", line 19, in __init__
    self.setIcon(icon)
  File "/opt/xware-desktop/frontend/Widgets/_KdeSystemTrayIcon.py", line 485, in setIcon
    raise ValueError("only support theme icon.")
ValueError: only support theme icon.
```
======================== 结束 ========================

no third-party ppa added:
newly installed system,all packages updated

**Comment by volcanosc** [comment]
桌面环境为xfce 4.11

**Comment by Xinkai** [comment]
这个问题已经修复了。重新编译打包一遍吧。

**Comment by volcanosc** [comment]
谢谢回复，重新编译打包问题已解决
