### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by milaneuo** [Xinkai/XwareDesktop#188]
======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/main.py", line 49, in slotSetting
    self.settingsDialog = SettingsDialog(self)
  File "/opt/xware-desktop/frontend/Settings/dialog.py", line 40, in __init__
    initType = getInitType()
  File "/opt/xware-desktop/frontend/utils/decorators.py", line 12, in wrap
    cached = func(*args, **kwargs)
  File "/opt/xware-desktop/frontend/utils/system.py", line 24, in getInitType
    with subprocess.Popen(["init", "--version"], stdout = subprocess.PIPE) as proc:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'init'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
为什么把操作系统的信息截去了？这样我不知道原因啊。

**Comment by milaneuo** [comment]
不好意思。
  lsb_release -a的结果是
Distributor ID:	LinuxMint
Description:	LMDE 2 Betsy
Release:	2
Codename:	betsy

uname -r的结果是
3.16.0-4-amd64

**Comment by Xinkai** [comment]
还有Xware Desktop的版本。。。建议你重新打开设置，让它崩溃一次。这次发个完整的～

**Comment by milaneuo** [comment]
xware-desktop_0.11.20140723_amd64
完整的错误日志如下

发行版: LinuxMint LMDE 2 Betsy 2 betsy 
桌面环境: default
版本: b8974b512f9b43336fe2bc86f27143f6b2cfd4f5

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/main.py", line 49, in slotSetting
    self.settingsDialog = SettingsDialog(self)
  File "/opt/xware-desktop/frontend/Settings/dialog.py", line 40, in __init__
    initType = getInitType()
  File "/opt/xware-desktop/frontend/utils/decorators.py", line 12, in wrap
    cached = func(*args, **kwargs)
  File "/opt/xware-desktop/frontend/utils/system.py", line 24, in getInitType
    with subprocess.Popen(["init", "--version"], stdout = subprocess.PIPE) as proc:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'init'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
版本太旧了。这个已经修复了。
你可以参考Wiki里的方法，重新打包。

**Comment by Xinkai** [comment]
https://github.com/Xinkai/XwareDesktop/wiki/Ubuntu%E4%B8%8A%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E
