### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by rookiecc** [Xinkai/XwareDesktop#193]
======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 86, in __init__
    from Notify import Notifier
  File "/opt/xware-desktop/frontend/Notify/__init__.py", line 7, in <module>
    from ._DBusNotifier import Notifier
  File "/opt/xware-desktop/frontend/Notify/_DBusNotifier.py", line 8, in <module>
    from PyQt5.QtMultimedia import QSound
ImportError: No module named 'PyQt5.QtMultimedia'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
什么操作系统？什么版本

**Comment by rookiecc** [comment]
你好，
      很高兴收到你的来信，我是ubuntu14.04lst python是2.7的是不是python需要3.4以上呢？







在 2015-06-24 22:59:26，"Xinkai Chen" <notifications@github.com> 写道：


什么操作系统？什么版本

**Comment by Xinkai** [comment]
请看Wiki上的Ubuntu的安装说明。
不要自己make make install

**Comment by rookiecc** [comment]
好的，谢谢。






在 2015-06-25 12:00:49，"Xinkai Chen" <notifications@github.com> 写道：


请看Wiki上的Ubuntu的安装说明。
不要自己make make install
