### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yang-le** [Xinkai/XwareDesktop#198]
发行版: Ubuntu 14.04.2 LTS 14.04
桌面环境: Unity/ubuntu
应用程序版本: 0c693745567dc5e831f1c99ccd6edc7d386f1db1

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/Widgets/monitor.py", line 43, in advance
    task = next(self._taskIterator)
  File "/opt/xware-desktop/frontend/Widgets/monitor.py", line 50, in _runningTasksIterator
    for id_, item in adapterMap.items():
  File "/opt/xware-desktop/frontend/models/AdapterMap.py", line 17, in items
    for rid, item in klassMap.items():
  File "/usr/lib/python3.4/_collections_abc.py", line 485, in __iter__
    yield (key, self._mapping[key])
  File "/opt/xware-desktop/frontend/models/KlassMap.py", line 55, in __getitem__
    raise KeyError("Cannot find {key} from KlassMap".format(key = rid))
KeyError: 'Cannot find xware-legacy|21 from KlassMap'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
是删除/移动某个任务后发生的么？

**Comment by yang-le** [comment]
抱歉啊，这个真的记不太清了，貌似是吧...
