### ISSUE TITLE
archlinux 安完xware-desktop后,第一次运行就出错

### ISSUE THREAD

**Issue by gbcbooks** [Xinkai/XwareDesktop#201]
发行版: Arch Linux 
桌面环境: KDE/kde-plasma
应用程序版本: 823f232dbd6f64fadc42388ccb8bb3bad4404046

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 86, in __init__
    from Notify import Notifier
  File "/opt/xware-desktop/frontend/Notify/__init__.py", line 7, in <module>
    from ._DBusNotifier import Notifier
  File "/opt/xware-desktop/frontend/Notify/_DBusNotifier.py", line 8, in <module>
    from PyQt5.QtMultimedia import QSound
ImportError: /usr/lib/libQt5Multimedia.so.5: undefined symbol: _ZN6QDebug9putStringEPK5QCharm
```
======================== 结束 ========================

**Comment by gbcbooks** [comment]
by the way , my OS is 64 bit

**Comment by Xinkai** [comment]
我用的也是Arch. 试试重装相关的包吧.
也可以试试重新编译本程序试试
如果还有问题 告诉我然后再讨论
