### ISSUE TITLE
编译完后安装出错

### ISSUE THREAD

**Issue by osdebianly** [Xinkai/XwareDesktop#205]
发行版: Linux Mint LMDE 
桌面环境: X-Cinnamon/default
应用程序版本: 823f232dbd6f64fadc42388ccb8bb3bad4404046

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 86, in __init__
    from Notify import Notifier
  File "/opt/xware-desktop/frontend/Notify/__init__.py", line 7, in <module>
    from ._DBusNotifier import Notifier
  File "/opt/xware-desktop/frontend/Notify/_DBusNotifier.py", line 8, in <module>
    from PyQt5.QtMultimedia import QSound
ImportError: No module named 'PyQt5.QtMultimedia'
```
======================== 结束 ========================

**Comment by osdebianly** [comment]
教程没看完，使用 sudo gdebi xware-desktop_0.13.20141115_amd64.deb  ok
