### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by wuyabei** [Xinkai/XwareDesktop#207]
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/Tasks/watchers/clipboard.py", line 29, in slotClipboardDataChanged
    self.agent.createTasksFromMimeData(mimeData)
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 82, in createTasksFromMimeData
    self.createTasksAction(urls)
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 88, in createTasksAction
    alltasks = self._filterInvalidTasks(map(self._createTask, taskUrls))
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 105, in _filterInvalidTasks
    return list(filter(lambda t: t is not None, tasks))
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 117, in _createTask
    url = misc.decodePrivateLink(taskUrl)
  File "/opt/xware-desktop/frontend/utils/misc.py", line 28, in decodePrivateLink
    decoded = base64.urlsafe_b64decode(path).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 34: invalid start byte
```

**Comment by Xinkai** [comment]
剪贴板监控的问题。能贴出来当时复制了什么东西么？
