### ISSUE TITLE
错误发生在MainThread

### ISSUE THREAD

**Issue by e-securite** [Xinkai/XwareDesktop#208]
发行版: elementary OS Freya 0.3
桌面环境: Pantheon/pantheon
应用程序版本: 823f232dbd6f64fadc42388ccb8bb3bad4404046

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 85, in __init__
    from Widgets.systray import Systray
  File "/opt/xware-desktop/frontend/Widgets/__init__.py", line 15, in <module>
    from ._KdeSystemTrayIcon import KdeSystemTrayIcon as CompatSystemTrayIcon
  File "/opt/xware-desktop/frontend/Widgets/_KdeSystemTrayIcon.py", line 12, in <module>
    from Extensions.DBusTypes import DBusTypes
ImportError: libDBusTypes.so.1: 无法打开共享对象文件: 没有那个文件或目录
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
重新编译打包一次试试吧
