### ISSUE TITLE
Ubuntu 15.04 启动错误

### ISSUE THREAD

**Issue by studycwq** [Xinkai/XwareDesktop#212]
发行版: Ubuntu 15.04 15.04
桌面环境: Unity/ubuntu
应用程序版本: 823f232dbd6f64fadc42388ccb8bb3bad4404046

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 86, in __init__
    from Notify import Notifier
  File "/opt/xware-desktop/frontend/Notify/__init__.py", line 7, in <module>
    from ._DBusNotifier import Notifier
  File "/opt/xware-desktop/frontend/Notify/_DBusNotifier.py", line 8, in <module>
    from PyQt5.QtMultimedia import QSound
ImportError: No module named 'PyQt5.QtMultimedia'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
把这个依赖装上应该就可以了

**Comment by studycwq** [comment]
解决了 用gdebi安装就可以了
