### ISSUE TITLE
ETM没有启动，同时挂载也有问题

### ISSUE THREAD

**Issue by oyvfhp** [Xinkai/XwareDesktop#214]
日志错误：
2015-09-09 18:53:09,487 ERROR:root:get/post settings failed.
2015-09-09 18:53:10,481 ERROR:root:get_getsysinfo failed. 
2015-09-09 18:53:10,481 ERROR:root:get_list failed.       
2015-09-09 18:53:10,482 ERROR:root:get_list failed.       
2015-09-09 18:53:10,482 ERROR:root:get_list failed.       
2015-09-09 18:53:10,483 ERROR:root:get_list failed. 

同时无法启动ETM：
![2015-09-09 18 58 13](https://cloud.githubusercontent.com/assets/4404279/9760123/e7557a2c-5724-11e5-9f83-34bed2b035eb.png)

同时挂载也报错：
![2015-09-09 18 59 20](https://cloud.githubusercontent.com/assets/4404279/9760161/4e92c53c-5725-11e5-8e01-a5a91f65528d.png)

**Comment by oyvfhp** [comment]
真心没人在吗？？？？

**Comment by Xinkai** [comment]
不知道你什么发行版。。
先把xwared关掉，然后在命令行执行`/opt/xware-desktop/xwared`，贴一下结果吧

**Comment by oyvfhp** [comment]
发行版: Ubuntu 15.04 15.04
桌面环境: Unity/ubuntu
应用程序版本: 2baa049c2f7ed0060cb6eeb858e432aa3f7d862d

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 281, in <module>
    profileBootstrap(constants.PROFILE_DIR)
  File "/opt/xware-desktop/frontend/../shared/profile.py", line 20, in profileBootstrap
    (profilePath / "cfg" / fileName).touch()
  File "/usr/lib/python3.4/pathlib.py", line 1091, in touch
    fd = self._raw_open(flags, mode)
  File "/usr/lib/python3.4/pathlib.py", line 952, in _raw_open
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.4/pathlib.py", line 322, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/home/mijon/.xware-desktop/profile/cfg/etm.cfg'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
不清楚为什么会权限错误

**Comment by oyvfhp** [comment]
恩，我已经给了他777的权限了，还是不行。

**Comment by oyvfhp** [comment]
mijon@mijon:cfg$ /opt/xware-desktop/xwared                                                                                                     │
xwared: unlocked                                                                                                                               │
错误：已经载入chmns。                                                                                                                          │
错误：已经载入chmns。                                                                                                                          │
错误：已经载入chmns。                                                                                                                          │
xwared: ETM持续时间连续3次不超过30秒，终止执行ETM                                                                                              │
这极有可能是xware本身的bug引起的，更多信息请看 https://github.com/Xinkai/XwareDesktop/wiki/故障排查和意见反馈#etm持续时间连续3次不超过30秒终止 │
执行etm的调试方法

**Comment by oyvfhp** [comment]
我看了一下你这个配置，用的是9000端口，我的9000端口已经被占用了，能不能改掉？

**Comment by oyvfhp** [comment]
我改了一下端口，再去测试发现一直在重复执行
[2015-09-16 16:52:48:421]: running disk detector...
Xware Desktop: FOPEN64 on /proc/mounts
[2015-09-16 16:52:48:421]: statfs(This): 2.
[2015-09-16 16:52:48:421]: running scheduler...

这是否正常？

**Comment by oyvfhp** [comment]
问题解决了，确实是因为占用了9000端口的问题，但无语的是这报错提示啊。。。。
这个端口是可以改变的，我改成了9111端口也可以运行。

关闭问题了。
