### ISSUE TITLE
issues，程序启动错误

### ISSUE THREAD

**Issue by iamdennisme** [Xinkai/XwareDesktop#218]
发行版: Ubuntu 14.04.3 LTS 14.04
桌面环境: Unity/ubuntu
应用程序版本: 开发版

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 57, in __init__
    self.checkOneInstance()
  File "/usr/bin/xware-desktop", line 137, in checkOneInstance
    fd = os.open(constants.FRONTEND_LOCK, os.O_RDWR | os.O_CREAT)
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/dennis/.xware-desktop/profile/tmp/xware_frontend.lock'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
重新启动下看会不会好
