### ISSUE TITLE
错误发生在MainThread

### ISSUE THREAD

**Issue by jinelei** [Xinkai/XwareDesktop#228]
发行版: Arch Linux 
桌面环境: XFCE/xfce
应用程序版本: 823f232dbd6f64fadc42388ccb8bb3bad4404046

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/Widgets/monitor.py", line 43, in advance
    task = next(self._taskIterator)
  File "/opt/xware-desktop/frontend/Widgets/monitor.py", line 50, in _runningTasksIterator
    for id_, item in adapterMap.items():
  File "/opt/xware-desktop/frontend/models/AdapterMap.py", line 17, in items
    for rid, item in klassMap.items():
  File "/usr/lib/python3.5/_collections_abc.py", line 676, in __iter__
    for key in self._mapping:
  File "/opt/xware-desktop/frontend/models/KlassMap.py", line 59, in __iter__
    yield from taskMap
RuntimeError: OrderedDict mutated during iteration
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
一直有这个问题吗？
