### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CLCX** [Xinkai/XwareDesktop#230]
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/frontendpy.py", line 151, in xdjsLoaded
    self.isXdjsLoaded = True
  File "/opt/xware-desktop/frontend/frontendpy.py", line 93, in isXdjsLoaded
    self.consumeAction("xdjs loaded")
  File "/opt/xware-desktop/frontend/frontendpy.py", line 194, in consumeAction
    print("Try to consume, because {}.".format(reason))
OSError: [Errno 5] 输入/输出错误

**Comment by Xinkai** [comment]
Ubuntu问题 认了吧
