### ISSUE TITLE
同时下载多个任务时， 一个任务完成时程序崩溃

### ISSUE THREAD

**Issue by bangbao** [Xinkai/XwareDesktop#236]
发行版: Ubuntu 16.04 16.04
桌面环境: Unity/ubuntu
应用程序版本: 2baa049c2f7ed0060cb6eeb858e432aa3f7d862d

补充描述计算机。
u

简述在什么情况下发生了这个问题。
同时下载多个任务时， 一个任务完成时崩溃
======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/Widgets/monitor.py", line 43, in advance
    task = next(self._taskIterator)
  File "/opt/xware-desktop/frontend/Widgets/monitor.py", line 50, in _runningTasksIterator
    for id_, item in adapterMap.items():
  File "/opt/xware-desktop/frontend/models/AdapterMap.py", line 17, in items
    for rid, item in klassMap.items():
  File "/usr/lib/python3.5/_collections_abc.py", line 676, in __iter__
    for key in self._mapping:
  File "/opt/xware-desktop/frontend/models/KlassMap.py", line 59, in __iter__
    yield from taskMap
RuntimeError: OrderedDict mutated during iteration
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
的确是有这个bug.. 欢迎patch
