### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by mr-tan4** [Xinkai/XwareDesktop#242]
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 86, in __init__
    from Notify import Notifier
  File "/opt/xware-desktop/frontend/Notify/__init__.py", line 7, in <module>
    from ._DBusNotifier import Notifier
  File "/opt/xware-desktop/frontend/Notify/_DBusNotifier.py", line 8, in <module>
    from PyQt5.QtMultimedia import QSound
ImportError: No module named 'PyQt5.QtMultimedia'

**Comment by Xinkai** [comment]
不要make, make install
生成安装包之后，并安装。
