### ISSUE TITLE
xware-desktop error and 

### ISSUE THREAD

**Issue by ywenming** [Xinkai/XwareDesktop#245]
发行版: Fedora 23 (Workstation Edition) 23
桌面环境: GNOME/gnome
应用程序版本: 开发版

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 57, in __init__
    self.checkOneInstance()
  File "/usr/bin/xware-desktop", line 137, in checkOneInstance
    fd = os.open(constants.FRONTEND_LOCK, os.O_RDWR | os.O_CREAT)
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/wenming/.xware-desktop/profile/tmp/xware_frontend.lock'
```
======================== 结束 ========================
i creat the tmp .
ok.
but.
![Uploading 2015-12-18 10-09-36 的屏幕截图.png…]()
xwared,etm,web .is red .

**Comment by ywenming** [comment]
[wenming@localhost ~]$ xware-desktop 

Qt[WARN] default None in None, on line 0
    QSoundEffect(pulseaudio): Error decoding source
Vector smash protection is enabled.
