### ISSUE TITLE
今天git更新的启动出现错误

### ISSUE THREAD

**Issue by moboard** [Xinkai/XwareDesktop#246]
发行版: Manjaro Linux 
桌面环境: X-Cinnamon/cinnamon
应用程序版本: ac48031fafa594fdc3ecad1634378626e8efd6dc

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'adapter-legacy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 79, in __init__
    self.adapterManager.loadAdapter(item)
  File "/opt/xware-desktop/frontend/models/AdapterManager.py", line 51, in loadAdapter
    if adapterConfig["type"] == "xware":
  File "/opt/xware-desktop/frontend/../shared/config.py", line 83, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/lib/python3.5/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.5/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'adapter-legacy'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
把`/opt/xware-desktop/frontend/../shared/config.py`83行附近的
```python3
        return self._parser.get(self._name, key)
```
换成
```python3
        return self._parser.myGet(self._name, key)
```
试一下～～

**Comment by sany98215** [comment]
发行版: Ubuntu 14.04.3 LTS 14.04
桌面环境: XFCE/xfce
应用程序版本: ac48031fafa594fdc3ecad1634378626e8efd6dc

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/configparser.py", line 1116, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 106, in __init__
    app = self)
  File "/opt/xware-desktop/frontend/legacy/main.py", line 28, in __init__
    self.preserveGeometry()
  File "/opt/xware-desktop/frontend/PersistentGeometry/__init__.py", line 13, in preserveGeometry
    savedGeometry = app.settings.getobj("internal", self._geometryKeyname())
  File "/opt/xware-desktop/frontend/../shared/config.py", line 44, in getobj
    pickledStr = self.get(section, key)
  File "/usr/lib/python3.4/configparser.py", line 754, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.4/configparser.py", line 1119, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'internal'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
@sany98215 把44行的getobj里面的get也变成myGet

**Comment by sany98215** [comment]
发行版: Ubuntu 14.04.3 LTS 14.04
桌面环境: XFCE/xfce
应用程序版本: ac48031fafa594fdc3ecad1634378626e8efd6dc

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/configparser.py", line 1116, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'frontend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/Tasks/watchers/clipboard.py", line 22, in slotWatchClipboardToggled
    on = app.settings.getbool("frontend", "watchclipboard")
  File "/opt/xware-desktop/frontend/../shared/config.py", line 37, in getbool
    return True if self.get(section, key) in ("1", True) else False
  File "/usr/lib/python3.4/configparser.py", line 754, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.4/configparser.py", line 1119, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'frontend'
```
======================== 结束 ========================

37行也要改么？？？？

**Comment by sany98215** [comment]
发行版: Ubuntu 14.04.3 LTS 14.04
桌面环境: XFCE/xfce
应用程序版本: ac48031fafa594fdc3ecad1634378626e8efd6dc

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/legacy/frontendpy.py", line 155, in xdjsLoaded
    self.tryLogin()
  File "/opt/xware-desktop/frontend/legacy/frontendpy.py", line 98, in tryLogin
    print(self.__adapterSettings.addons_loaded, "<-- loaded")
  File "/opt/xware-desktop/frontend/../shared/config.py", line 69, in __getattr__
    raise AttributeError("Cannot find {}".format(item))
AttributeError: Cannot find addons_loaded
```
======================== 结束 ========================
