### ISSUE TITLE
安装后启动失败

### ISSUE THREAD

**Issue by sany98215** [Xinkai/XwareDesktop#247]
发行版: Ubuntu 14.04.3 LTS 14.04
桌面环境: XFCE/xfce
应用程序版本: ac48031fafa594fdc3ecad1634378626e8efd6dc

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/configparser.py", line 1116, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'adapter-legacy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 79, in __init__
    self.adapterManager.loadAdapter(item)
  File "/opt/xware-desktop/frontend/models/AdapterManager.py", line 51, in loadAdapter
    if adapterConfig["type"] == "xware":
  File "/opt/xware-desktop/frontend/../shared/config.py", line 83, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/lib/python3.4/configparser.py", line 754, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.4/configparser.py", line 1119, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'adapter-legacy'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
重复问题，请关注 #246
