### ISSUE TITLE
KeyError: 'internal'

### ISSUE THREAD

**Issue by lisuke** [Xinkai/XwareDesktop#249]
发行版: Ubuntu Kylin 15.04 15.04
桌面环境: Unity/ubuntu
应用程序版本: ac48031fafa594fdc3ecad1634378626e8efd6dc

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/configparser.py", line 1116, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 106, in __init__
    app = self)
  File "/opt/xware-desktop/frontend/legacy/main.py", line 28, in __init__
    self.preserveGeometry()
  File "/opt/xware-desktop/frontend/PersistentGeometry/__init__.py", line 13, in preserveGeometry
    savedGeometry = app.settings.getobj("internal", self._geometryKeyname())
  File "/opt/xware-desktop/frontend/../shared/config.py", line 44, in getobj
    pickledStr = self.get(section, key)
  File "/usr/lib/python3.4/configparser.py", line 754, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.4/configparser.py", line 1119, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'internal'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
#246
