### ISSUE TITLE
why show it????

### ISSUE THREAD

**Issue by zhongstudio** [Xinkai/XwareDesktop#270]
发行版: Ubuntu Ubuntu 14.04.2 LTS 14.04 trusty 
桌面环境: ubuntu
版本: a8be40a81f82aacd4877090a6149b75b86b26d78

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在frontend communication listener
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/CrashReport/CrashAwareThreading.py", line 23, in new_run
    self._unpatched_run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/xware-desktop/frontend/Tasks/watchers/commandline.py", line 36, in listenerThread
    self.agent.createTasksAction(payload)
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 88, in createTasksAction
    alltasks = self._filterInvalidTasks(map(self._createTask, taskUrls))
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 105, in _filterInvalidTasks
    return list(filter(lambda t: t is not None, tasks))
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 117, in _createTask
    url = misc.decodePrivateLink(taskUrl)
  File "/opt/xware-desktop/frontend/utils/misc.py", line 28, in decodePrivateLink
    decoded = base64.urlsafe_b64decode(path).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 35: invalid start byte
```
======================== 结束 ========================

**Comment by zhongstudio** [comment]
sorry i make mistake!
folder properties not settings
