### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shenyefeng** [Xinkai/XwareDesktop#276]
发行版: Debian Debian GNU/Linux 8.2 (jessie) 8.2 jessie 
桌面环境: default
版本: b8974b512f9b43336fe2bc86f27143f6b2cfd4f5

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/main.py", line 49, in slotSetting
    self.settingsDialog = SettingsDialog(self)
  File "/opt/xware-desktop/frontend/Settings/dialog.py", line 40, in __init__
    initType = getInitType()
  File "/opt/xware-desktop/frontend/utils/decorators.py", line 12, in wrap
    cached = func(*args, **kwargs)
  File "/opt/xware-desktop/frontend/utils/system.py", line 24, in getInitType
    with subprocess.Popen(["init", "--version"], stdout = subprocess.PIPE) as proc:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'init'
```
======================== 结束 ========================

**Comment by shenyefeng** [comment]
after add sudo , error does not show
