### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by newboydj169** [Xinkai/XwareDesktop#278]
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/main.py", line 49, in slotSetting
    self.settingsDialog = SettingsDialog(self)
  File "/opt/xware-desktop/frontend/Settings/dialog.py", line 40, in __init__
    initType = getInitType()
  File "/opt/xware-desktop/frontend/utils/decorators.py", line 12, in wrap
    cached = func(*args, **kwargs)
  File "/opt/xware-desktop/frontend/utils/system.py", line 24, in getInitType
    with subprocess.Popen(["init", "--version"], stdout = subprocess.PIPE) as proc:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'init'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
本项目不再维护
