### ISSUE TITLE
Errors on linux mint 17.3 Rosa

### ISSUE THREAD

**Issue by zzyyxxjc** [Xinkai/XwareDesktop#279]
发行版: LinuxMint Linux Mint 17.3 Rosa 17.3 rosa 
桌面环境: xfce
版本: b8974b512f9b43336fe2bc86f27143f6b2cfd4f5

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 207, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 72, in __init__
    self.frontendpy = FrontendPy(self)
  File "/opt/xware-desktop/frontend/frontendpy.py", line 48, in __init__
    self.taskCreationAgent = TaskCreationAgent(self)  # just hold a reference
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 65, in __init__
    self.createTasksAction(tasks)
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 88, in createTasksAction
    alltasks = self._filterInvalidTasks(map(self._createTask, taskUrls))
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 105, in _filterInvalidTasks
    return list(filter(lambda t: t is not None, tasks))
  File "/opt/xware-desktop/frontend/Tasks/action.py", line 117, in _createTask
    url = misc.decodePrivateLink(taskUrl)
  File "/opt/xware-desktop/frontend/utils/misc.py", line 29, in decodePrivateLink
    decoded = base64.urlsafe_b64decode(path).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 15: invalid start byte
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
本项目不再维护
