### ISSUE TITLE
什么问题？

### ISSUE THREAD

**Issue by jasontj** [Xinkai/XwareDesktop#280]
发行版: Ubuntu 15.10 15.10
桌面环境: Unity/ubuntu
应用程序版本: 408a451b1548864ff5073e60c52e62082d2219cf

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 85, in __init__
    from Widgets.systray import Systray
  File "/opt/xware-desktop/frontend/Widgets/__init__.py", line 15, in <module>
    from ._KdeSystemTrayIcon import KdeSystemTrayIcon as CompatSystemTrayIcon
  File "/opt/xware-desktop/frontend/Widgets/_KdeSystemTrayIcon.py", line 12, in <module>
    from Extensions.DBusTypes import DBusTypes
ImportError: libDBusTypes.so.1: 无法打开共享对象文件: 没有那个文件或目录
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
不再维护
